name: Foundational DevOps Pipeline

# 1. Trigger the workflow on every push to the main branch
on:
  push:
    branches: [main]

# 2. Define the execution track
jobs:
  code-verification:
    # This must have exactly 4 spaces to align under the job block
    runs-on: ubuntu-latest

    steps:
      # Each dash (-) inside steps must align perfectly under the 's' of steps
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      # Step 1: Log in to Docker Hub using Github Secrets Securely
      - name: Log into Docker Hub
        uses: docker/login-actions@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 2: Set up Docker Buildx (Advanced builder engine engine for caching)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-actions@v3


      # Step 3: Build the multi-stage image and push it to public registry

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          # Tell it to look inside our day for multi-stage folder
          context: ./devops_day_17_docker_multistage
          file: ./devops_day_17_docker_multistage/Dockerfile
          push: true
          # Tagging the image under Docker Hub username
          tags: gauravbanga/multistage-test:latest

      - name: Run System Diagnostics Scan
        run: |
          echo "================================="
          echo "Starting Automated Cloud Security Scan....."
          echo "Current Repository Workspace: $GITHUB_WORKSPACE"
          echo "Triggered By Github Actor: $GITHUB_ACTOR"
          echo "======================================="

      - name: Verify Repository Architecture Integrity
        run: |
          ls -la
          echo "Verification Check: SUCCESS"
